/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package teste;

import ligarcarro.Carro;

/**
 *
 * @author adm
 */
public class JLigar_Carro extends javax.swing.JFrame {

    /**
     * Creates new form JCarro
     */
    public JLigar_Carro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnacelerar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtcor = new javax.swing.JTextField();
        txtmodelo = new javax.swing.JTextField();
        txtmotor = new javax.swing.JTextField();
        btnoff = new javax.swing.JButton();
        btnligar2 = new javax.swing.JButton();
        boxvel = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lblresp = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnacelerar.setText("Acelerar");
        btnacelerar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnacelerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnacelerarActionPerformed(evt);
            }
        });
        getContentPane().add(btnacelerar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, 60, 20));

        jLabel4.setFont(new java.awt.Font("Rockwell Extra Bold", 3, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Cor");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 70, 40));
        getContentPane().add(txtcor, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 140, -1));
        getContentPane().add(txtmodelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 140, -1));

        txtmotor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmotorActionPerformed(evt);
            }
        });
        getContentPane().add(txtmotor, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 140, -1));

        btnoff.setText("Desligar");
        btnoff.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnoff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnoffActionPerformed(evt);
            }
        });
        getContentPane().add(btnoff, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, 60, 20));

        btnligar2.setText("Ligar");
        btnligar2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnligar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnligar2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnligar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 60, 20));

        boxvel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10", "20", "30", "40" }));
        boxvel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boxvel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxvelActionPerformed(evt);
            }
        });
        getContentPane().add(boxvel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, 80, 20));

        jButton3.setText("Enviar");
        jButton3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 60, 20));

        jLabel9.setFont(new java.awt.Font("Rockwell Extra Bold", 3, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("Ligar carro :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 110, 40));

        jLabel10.setFont(new java.awt.Font("Rockwell Extra Bold", 3, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("Motor");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 70, 40));

        jLabel11.setFont(new java.awt.Font("Rockwell Extra Bold", 3, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("Modelo");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 70, 40));

        jLabel12.setFont(new java.awt.Font("Rockwell Extra Bold", 3, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("Acelerar :");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 90, 40));

        jLabel3.setFont(new java.awt.Font("Rockwell Extra Bold", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ESCOLHA O SEU CARRO");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 280, 40));

        lblresp.setColumns(20);
        lblresp.setRows(5);
        jScrollPane1.setViewportView(lblresp);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 300, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teste/car.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, -10, 420, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents
  Carro car = new Carro();
        String carros = "";
        
        public void Limpar(){
            txtmotor.setText("");
            txtcor.setText("");
            txtmodelo.setText("");
            txtmotor.requestFocus();
        }
        
    private void btnacelerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnacelerarActionPerformed
        int indexvelocidade = boxvel.getSelectedIndex();
        if(car.getLigar()){
            switch(indexvelocidade){
                case 0:
                lblresp.setText("Velocidade atual: " + car.Acelerar(10));
                System.out.println(car.getVelocidade());
                break;
                case 1:
                lblresp.setText("Velocidade atual: " + car.Acelerar(20));
                break;
                case 2:
                lblresp.setText("Velocidade atual: " + car.Acelerar(30));
                break;
                case 3:
                lblresp.setText("Velocidade atual: " +  car.Acelerar(40));
                break;
            }
        }
        else
        lblresp.setText(" Ligue o carro primeiro.");
    }//GEN-LAST:event_btnacelerarActionPerformed

    private void btnoffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnoffActionPerformed
        lblresp.setText(" Desligando o carro...");
        car.DesligarCarro(false);
    }//GEN-LAST:event_btnoffActionPerformed

    private void btnligar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnligar2ActionPerformed
        if(car.getLigar()){  //já que não tem parâmetro entende-se como TRUE
            lblresp.setText(" O carro já está ligado");
        }
        else
        lblresp.setText(" Ligando o carro...");
        car.LigarCarro(true);
    }//GEN-LAST:event_btnligar2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        double motor = Double.parseDouble(txtmotor.getText());

        car.setCor(txtcor.getText());
        car.setModelo(txtmodelo.getText());
        car.setMotor(motor);

        lblresp.setText(car.exibirdados());
        Limpar();

    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtmotorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmotorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmotorActionPerformed

    private void boxvelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxvelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxvelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JLigar_Carro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JLigar_Carro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JLigar_Carro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JLigar_Carro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JLigar_Carro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxvel;
    private javax.swing.JButton btnacelerar;
    private javax.swing.JButton btnligar2;
    private javax.swing.JButton btnoff;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea lblresp;
    private javax.swing.JTextField txtcor;
    private javax.swing.JTextField txtmodelo;
    private javax.swing.JTextField txtmotor;
    // End of variables declaration//GEN-END:variables
}
