/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Aula130821;

/**
 *
 * @author Guilherme
 */
public class JEleicao extends javax.swing.JFrame {

    /**
     * Creates new form JEleicao
     */
    public JEleicao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        B1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        B2 = new javax.swing.JButton();
        B3 = new javax.swing.JButton();
        respo = new javax.swing.JLabel();
        fim = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        B1.setText("Cand. 1");
        B1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 51, 0));
        jLabel1.setText("       Eleição 2021");

        B2.setText("Cand. 2");
        B2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B2ActionPerformed(evt);
            }
        });

        B3.setText("Cand. 3");
        B3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B3ActionPerformed(evt);
            }
        });

        respo.setText("...");

        fim.setText("Apuração");
        fim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fimActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(respo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(B1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addComponent(B2)
                        .addGap(26, 26, 26)
                        .addComponent(B3)))
                .addGap(48, 48, 48))
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(fim, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(fim, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(respo)
                .addGap(51, 51, 51))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
    
   
    int cand01 = 0, cand02=0, cand03=0;
    int[] candidatos = new int[3];//DECLARAÇÃO DE VETORES
    private void B2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B2ActionPerformed
        cand02++;
        candidatos[1] = cand02;
        System.out.println("Candidato 2 = " + cand02);
    }//GEN-LAST:event_B2ActionPerformed

    private void B1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B1ActionPerformed
    cand01++;
    candidatos [0] = cand01; //SOBRESCREVE O VALOR 0
    //candidatos [0] = candidatos[0] + 1;
    System.out.println("Candidato 1 =  " + cand01);
    }//GEN-LAST:event_B1ActionPerformed

    private void B3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B3ActionPerformed
        cand03++;
        candidatos [2] = candidatos[2]+1;
        System.out.println("Candidato 3 =  " + cand03);
    }//GEN-LAST:event_B3ActionPerformed

    private void fimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fimActionPerformed
        String resp = "";
        if(cand01 == cand02 && cand01 == cand03 && cand02 == cand03){
             System.out.println("Empate entre os 3 candidatos. SEM VENCEDORES"); 
             resp ="Empate entre os 3 candidatos. SEM VENCEDORES";
        }
      else if(cand01 == cand02){
           System.out.println("Candiado 1 e 2 empatados com " + cand01 + " votos");
           resp = "Candiado 1 e 2 empatados com " + cand01 + " votos";
         }
       else if(cand01 == cand03){
            System.out.println("Candiado 1 e 3 empatados com " + cand01 + " votos");
            resp = "Candiado 1 e 3 empatados com " + cand01 + " votos";
       }
       else if(cand02 == cand03){
            System.out.println("Candiado 2 e 3 empatados com " + cand03 + " votos");
            resp = "Candiado 2 e 3 empatados com " + cand03 + " votos";
       }
         if(cand01>cand02 && cand01>cand03){
           System.out.println("Candidato 1 ganhou com : "+ cand01 +" votos");
           resp = "Candidato 1 ganhou com : "+ cand01 +" votos";
       }
        if(cand02>cand01 && cand02>cand03){
           System.out.println("Candidato 2 ganhou com : "+ cand02  +" votos");
           resp = "Candidato 2 ganhou com : "+ cand02  +" votos";
       }
        if(cand03>cand01 && cand03>cand02){
           System.out.println("Candidato 3 ganhou com : "+ cand03  +" votos");
           resp = "Candidato 3 ganhou com : "+ cand03  +" votos";
       }
        respo.setText(resp);//AQUI ELE DECLAROU UMA VAR. STRING PARA ENVIAR P O LABEL.
      
    }//GEN-LAST:event_fimActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JEleicao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JEleicao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JEleicao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JEleicao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new JEleicao().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B1;
    private javax.swing.JButton B2;
    private javax.swing.JButton B3;
    private javax.swing.JButton fim;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel respo;
    // End of variables declaration//GEN-END:variables
}
