/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testes_classes;

import ligar_carro.Carro;

/**
 *
 * @author adm
 */
public class JLigar_Carro extends javax.swing.JFrame {

    /**
     * Creates new form JLigar_Carro
     */
    public JLigar_Carro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnacelerar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtcor = new javax.swing.JTextField();
        txtmodelo = new javax.swing.JTextField();
        txtmotor = new javax.swing.JTextField();
        btnoff = new javax.swing.JButton();
        btnligar2 = new javax.swing.JButton();
        boxvel = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblresp = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        jLabel5.setText("Cor");

        jLabel6.setText("Modelo");

        jLabel8.setText("Acelerar");

        jLabel7.setText("Ligue o carro aqui");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testes_classes/car.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnacelerar.setText("Acelerar");
        btnacelerar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnacelerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnacelerarActionPerformed(evt);
            }
        });
        getContentPane().add(btnacelerar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, 60, 20));

        jLabel3.setFont(new java.awt.Font("Rockwell Extra Bold", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ESCOLHA O SEU CARRO");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 280, 40));

        jLabel4.setFont(new java.awt.Font("Rockwell Extra Bold", 3, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Cor");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 70, 40));
        getContentPane().add(txtcor, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 140, -1));
        getContentPane().add(txtmodelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 140, -1));
        getContentPane().add(txtmotor, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 140, -1));

        btnoff.setText("Desligar");
        btnoff.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnoff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnoffActionPerformed(evt);
            }
        });
        getContentPane().add(btnoff, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, 60, 20));

        btnligar2.setText("Ligar");
        btnligar2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnligar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnligar2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnligar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 60, 20));

        boxvel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10", "20", "30", "40" }));
        boxvel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(boxvel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, 80, 20));

        jButton3.setText("Enviar");
        jButton3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 60, 20));

        jLabel9.setFont(new java.awt.Font("Rockwell Extra Bold", 3, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("Ligar carro :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 110, 40));

        jLabel10.setFont(new java.awt.Font("Rockwell Extra Bold", 3, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("Motor");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 70, 40));

        jLabel11.setFont(new java.awt.Font("Rockwell Extra Bold", 3, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("Modelo");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 70, 40));

        jLabel12.setFont(new java.awt.Font("Rockwell Extra Bold", 3, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("Acelerar :");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 90, 40));

        lblresp.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        lblresp.setForeground(new java.awt.Color(255, 255, 255));
        lblresp.setText("...");
        getContentPane().add(lblresp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 330, 80));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/car.jpg"))); // NOI18N
        jLabel13.setText("jLabel13");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(-80, -30, 500, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents
            
        Carro car = new Carro();
        String carros = "";
        
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        double motor = Double.parseDouble(txtmotor.getText());
        
        car.setCor(txtcor.getText());
        car.setModelo(txtmodelo.getText());
        car.setMotor(motor);
        
        lblresp.setText(car.exibirdados());
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnligar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnligar2ActionPerformed
        if(car.getLigar()){  //já que não tem parâmetro entende-se como TRUE
            lblresp.setText(" O carro já está ligado");
        }
        else
            lblresp.setText(" Ligando o carro...");
            car.LigarCarro(true);  
    }//GEN-LAST:event_btnligar2ActionPerformed

    private void btnacelerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnacelerarActionPerformed
        int indexvelocidade = boxvel.getSelectedIndex();
        if(car.getLigar()){
            switch(indexvelocidade){
                case 0:
                    lblresp.setText("Velocidade atual: " + car.Acelerar(10));
                    System.out.println(car.getVelocidade());
                    break;
                case 1:
                    lblresp.setText("Velocidade atual: " + car.Acelerar(20));
                    break;
                case 2:
                    lblresp.setText("Velocidade atual: " + car.Acelerar(30));
                    break;
                case 3:
                   lblresp.setText("Velocidade atual: " +  car.Acelerar(40));
                   break;
            }
        }
        else
            lblresp.setText(" Ligue o carro primeiro.");
    }//GEN-LAST:event_btnacelerarActionPerformed

    private void btnoffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnoffActionPerformed
        lblresp.setText(" Desligando o carro...");
        car.DesligarCarro(false);
    }//GEN-LAST:event_btnoffActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JLigar_Carro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JLigar_Carro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JLigar_Carro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JLigar_Carro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new JLigar_Carro().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxvel;
    private javax.swing.JButton btnacelerar;
    private javax.swing.JButton btnligar2;
    private javax.swing.JButton btnoff;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblresp;
    private javax.swing.JTextField txtcor;
    private javax.swing.JTextField txtmodelo;
    private javax.swing.JTextField txtmotor;
    // End of variables declaration//GEN-END:variables

    
}
