/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testes_classes;

import sistema_lavarRoupas.Roupas;

/**
 *
 * @author adm
 */
public class JRoupas extends javax.swing.JFrame {

    /**
     * Creates new form JRoupas
     */
    public JRoupas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txttipo = new javax.swing.JComboBox<>();
        txtcor = new javax.swing.JComboBox<>();
        txttam = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtresp = new javax.swing.JTextArea();
        btnadd = new javax.swing.JButton();
        btnseparar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jLabel2.setText("TIPO");

        jLabel4.setText("TAMANHO");

        jLabel7.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("COR");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("LAVE SUAS ROUPAS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 240, 28));

        txttipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Camisa", "Vestido", "Calça", "Sapato" }));
        getContentPane().add(txttipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 88, 105, 32));

        txtcor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Colorida", "Branca" }));
        getContentPane().add(txtcor, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 150, 105, 32));
        getContentPane().add(txttam, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 213, 105, -1));

        jLabel3.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("TIPO");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 40, -1));

        txtresp.setColumns(20);
        txtresp.setRows(5);
        jScrollPane1.setViewportView(txtresp);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 264, 327, -1));

        btnadd.setText("ADD");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });
        getContentPane().add(btnadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 378, 74, -1));

        btnseparar.setText("SEPARAR");
        btnseparar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsepararActionPerformed(evt);
            }
        });
        getContentPane().add(btnseparar, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 378, -1, -1));

        jLabel6.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("TAMANHO");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 80, -1));

        jLabel8.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("COR");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 40, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/washingmachine.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void Limpar(){
        txttam.setText("");
        txttam.requestFocus();
    }
    
    int plus = 0, quant = 0,valor = 0;
    boolean trocar = false;
    Roupas peça = new Roupas();
    String cor;
    String tipo, roupas="";
    boolean sap = false;
    
    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
  
        int indexcor = txtcor.getSelectedIndex();
        switch(indexcor){
            case 0:
                cor = "Colorida";
                trocar = false;
                break;
            
            case 1:
                cor = "Branca";
                trocar = true;
                plus = plus + 1;
                sap = true;
                break;
        }
        
        int indextipo = txttipo.getSelectedIndex();
        switch(indextipo){
            case 0:
                tipo = "Camisa";
                valor = 20 + valor;
                break;
            case 1:
                tipo ="Vestido";
                 valor = 30 + valor;
                break;
            case 2:
                tipo = "Calça";
                 valor = 40 + valor;
                break;
            case 3:
                tipo = "Sapato";
                quant = quant + 1;
                 valor = 50 + valor;
                 sap = true;
                break;
        }
        
        if(indextipo == 3){
            txtresp.setText("Esse item não vai na máquina, redirecione para o setor de calçados");
        }
        else{
        if(trocar){
            peça.setCor(cor);
            peça.setTipo(tipo);
            peça.setTamanho(txttam.getText());
            
            roupas += peça.exibir();
            txtresp.setText(roupas + " Essa peça será separada" + "\n" + "Valor da lavagem: "+ valor+ "\n");
      
        }
        
        else{
            peça.setCor(cor);
            peça.setTipo(tipo);
            peça.setTamanho(txttam.getText());
            
            roupas += peça.exibir();
            txtresp.setText(roupas + "Valor da lavagem: "+ valor);
        }
        }
        Limpar();
    }//GEN-LAST:event_btnaddActionPerformed

    private void btnsepararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsepararActionPerformed
        if(sap == true){
            if(quant != 0){
                 txtresp.setText(quant + " Itens irão para o setor de calçados" + "\n" + "Valor da lavagem: "+ valor  + "\n");
            }
            if(plus != 0){
                txtresp.setText(plus + " Itens irão para o setor de calçados" + "\n" + "Valor da lavagem: "+ valor + "\n");
            }
           
        }
        else{
            txtresp.setText("Todas as peças irão para o mesmo setor!");
        }
    }//GEN-LAST:event_btnsepararActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JRoupas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new JRoupas().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btnseparar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> txtcor;
    private javax.swing.JTextArea txtresp;
    private javax.swing.JTextField txttam;
    private javax.swing.JComboBox<String> txttipo;
    // End of variables declaration//GEN-END:variables

    private String exibir() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
