/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aula270821;

/**
 *
 * @author adm
 */
public class JOrdenacaoDeVetores extends javax.swing.JFrame {

    /**
     * Creates new form ordenacao_de_vetores
     */
    public JOrdenacaoDeVetores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtresp = new javax.swing.JTextField();
        btnadd = new javax.swing.JButton();
        btnexibir = new javax.swing.JButton();
        btnremover = new javax.swing.JButton();
        btnmaior = new javax.swing.JButton();
        btnmenor = new javax.swing.JButton();
        btncres = new javax.swing.JButton();
        btndec = new javax.swing.JButton();
        txtv = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Manipulando Vetores");

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel2.setText("Valor");

        btnadd.setText("ADD");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        btnexibir.setText("Exibir");
        btnexibir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexibirActionPerformed(evt);
            }
        });

        btnremover.setText("Remover");
        btnremover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnremoverActionPerformed(evt);
            }
        });

        btnmaior.setText("Maior");
        btnmaior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmaiorActionPerformed(evt);
            }
        });

        btnmenor.setText("Menor");
        btnmenor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmenorActionPerformed(evt);
            }
        });

        btncres.setText("Ordem CRES");
        btncres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncresActionPerformed(evt);
            }
        });

        btndec.setText("Ordem DECR");
        btndec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndecActionPerformed(evt);
            }
        });

        txtv.setText("...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(331, 331, 331)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(txtresp, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(btnadd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnexibir)
                        .addGap(18, 18, 18)
                        .addComponent(btnremover)
                        .addGap(18, 18, 18)
                        .addComponent(btnmaior)
                        .addGap(18, 18, 18)
                        .addComponent(btnmenor)
                        .addGap(18, 18, 18)
                        .addComponent(btncres)
                        .addGap(18, 18, 18)
                        .addComponent(btndec))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(txtv, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtresp, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnexibir, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnremover, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnmaior, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnmenor, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncres, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btndec, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(txtv, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    int valores []= new int[10]; /*DECLAREI O VETOR*/
       String resp = " ";/*STRING PARA DEFINIR A RESPOSTA*/
       int topo;/*TOPO - VARIÁVEL QUE VAI AUX. NA LEITURA DO VETOR, FAZENDO C Q LEIA ATÉ ONDE FOI USADO*/
       
       public String exibirelementos(){ /*UM MÉTODO PARA EXIBIR O ELEMENTO*/
           resp = "";
           for(int i = 0; i<topo; i++){
               resp = resp + " " + valores[i];
           }
           return resp;
       }
       
       public void Limpar(){ /*CRIEI UM MÉTODO LIMPAR*/
           txtv.setText("");       
           txtv.requestFocus();
       }
       
       public void addElementos(int valor){ /*UM MÉTODO PARA ADICIONAR OS ELEMENTOS*/
            for(int i = 0; i<valores.length; i++){
           if(valores[i]== 0){
            valores[i] = valor;
            //resp = resp + " " + valores[i];
            topo++;
          
            break;
        }            
       }
       }
       
       public boolean removerelemento(int valor){ /*AQUI EU VOU ESCOLHER UM ELEMENTO E EXCLUIR DO MEU VETOR*/
           boolean resp = false;
           for(int i= 0; i<topo; i++){
               if(valores[i] == valor){
                    valores[i] = 0;
                    resp = true;
                    topo--;  /*AQUI EU CONSIGO TIRAR O ELEMENTO 0*/
                    break;
               }
           }
           return resp;
       }
       
       public String maiorelemento(){
          int maior = -999;
           resp="";
           for(int i = 0; i<topo; i++){
               if(valores[i] > maior){
                   maior = valores[i];
                   resp = "O maior elemento é: " + maior;
               }
           }
           return resp;
       }
       
       public String menorelemento(){
           int menor = +999;
           resp="";
           for(int i = 0; i<topo; i++){
               if(valores[i] < menor){
                   menor = valores[i];
                   resp = "O menor valor é: " + menor;
               }
           }
         return resp;  
       }
       
       /*public void limpar(){
           txtresp.setText("");
           txtv.requestFocus();
           txtv.setText("");
           for(int i = 0; i<topo; i++){
               valores[i]=0;
               topo = 0;
           }
       } */
       
       public String crescente(){
         String respo ="";
         for(int i = 0; i<topo; i++){
             respo = respo + " " + valores[i]; 
         } 
         
         return respo;
       }
       
       public String decrescente(){
           String res = "";
           int maior;
           int posicao;
           boolean troca;
           int aux;
           for(int i =0; i<topo; i++){
               maior = valores[i];
               posicao = i;
               troca = false;
               for(int j = i+1; j<topo; j++){
                   if(maior < valores[j]){
                       maior = valores[j];
                       posicao = j;
                       troca = true;
                   }                  
               }   
               if(troca == true){
                       aux = valores[i];
                       valores[posicao] = aux;
                       valores[i] = maior;
                   }
           }
         for(int i = 0; i<topo; i++){
                   res = res + " " + valores[i];
               }
           return res;
       }
    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
         int valor = Integer.parseInt(txtv.getText());/*CONVERTENDO O VALOR STRING Q PEGUEI P INTER*/
        addElementos(valor);
        Limpar();
        txtresp.setText(exibirelementos());
        System.out.print(resp);
    }//GEN-LAST:event_btnaddActionPerformed

    private void btnexibirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexibirActionPerformed
        txtv.setText(exibirelementos());
    }//GEN-LAST:event_btnexibirActionPerformed

    private void btnremoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnremoverActionPerformed
        int valor = Integer.parseInt(txtresp.getText());
        if(removerelemento(valor)){
            txtv.setText("Valor retirado com sucesso");
        }else{
            txtv.setText("Valor não encontrado");
        }
    }//GEN-LAST:event_btnremoverActionPerformed

    private void btnmaiorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmaiorActionPerformed
        txtv.setText(maiorelemento());
    }//GEN-LAST:event_btnmaiorActionPerformed

    private void btnmenorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmenorActionPerformed
        txtv.setText(menorelemento());
    }//GEN-LAST:event_btnmenorActionPerformed

    private void btncresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncresActionPerformed
            crescente();
            txtv.setText(crescente());
    }//GEN-LAST:event_btncresActionPerformed

    private void btndecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndecActionPerformed
        decrescente();
       txtv.setText(decrescente());
    }//GEN-LAST:event_btndecActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JOrdenacaoDeVetores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JOrdenacaoDeVetores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JOrdenacaoDeVetores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JOrdenacaoDeVetores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new JOrdenacaoDeVetores().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btncres;
    private javax.swing.JButton btndec;
    private javax.swing.JButton btnexibir;
    private javax.swing.JButton btnmaior;
    private javax.swing.JButton btnmenor;
    private javax.swing.JButton btnremover;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtresp;
    private javax.swing.JLabel txtv;
    // End of variables declaration//GEN-END:variables
}
